MiniProject/WebApp/Controllers/TabAlamatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading.Tasks;
using ViewModel;
using WebApp.Services;

namespace WebApp.Controllers
{
    public class TabAlamatController : Controller
    {
        private readonly ILogger<TabAlamatController> _logger;
        private readonly IConfiguration _configuration;
        private readonly string WebApiBaseUrl;

        private readonly TabAlamatService TabServ;
        private readonly LocationService locserv;

        private List<ListValue> colList = new List<ListValue>()
            {
                new ListValue(){ Id = 1, Value = "biodata_id"},
                new ListValue(){ Id = 2, Value = "label"},
                new ListValue(){ Id = 3, Value = "recipient"},
                new ListValue(){ Id = 4, Value = "recipient_phone_number"},
                new ListValue(){ Id = 5, Value = "location_id"},
                new ListValue(){ Id = 6, Value = "postal_code"},
                new ListValue(){ Id = 7, Value = "address"}
            };

        public TabAlamatController(ILogger<TabAlamatController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
            WebApiBaseUrl = _configuration.GetValue<string>("WebApiBaseUrl");
            TabServ = new TabAlamatService(configuration);
            locserv = new LocationService(configuration);
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Create()
        {
            ResponseResult location = await locserv.Page(1, 100000, "");
            ViewBag.Location = new SelectList((List<LocationViewModel>)JsonConvert.DeserializeObject<List<LocationViewModel>>(location.Entity.ToString()), "id", "name");
            return PartialView("_Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create(TabAlamatViewModel model)
        {
            if (ModelState.IsValid)
            {
                ResponseResult result = await TabServ.Create(model);
                if (result.Success)
                {
                    ViewBag.title = "Create";
                    ViewBag.subtitle = "Created";
                    return PartialView("_Success", model);
                }
                else
                {
                    ViewBag.ErrorMessage = result.Message;
                }

            }
            ResponseResult location = await locserv.Page(1, 100000, "");
            ViewBag.Location = new SelectList((List<LocationViewModel>)JsonConvert.DeserializeObject<List<LocationViewModel>>(location.Entity.ToString()), "id", "name");
            return PartialView("_Create", model);
        }

        public async Task<IActionResult> Edit(int id)
        {

            ResponseResult result = await TabServ.GetById(id);
            if (result != null)
            {
                return PartialView("_Edit", result.Entity);
            }
            ResponseResult location = await locserv.Page(1, 100000, "");
            ViewBag.Location = new SelectList((List<LocationViewModel>)JsonConvert.DeserializeObject<List<LocationViewModel>>(location.Entity.ToString()), "id", "name");
            return PartialView("_Edit", result.Entity);

        }


        [HttpPost]
        public async Task<IActionResult> Edit(TabAlamatViewModel model)
        {
            if (ModelState.IsValid)
            {
                ResponseResult result = await TabServ.Update(model);

                if (result.Success)
                {
                    ViewBag.title = "Edit";
                    ViewBag.subtitle = "Edited";
                    return PartialView("_Success", model);
                }
                else
                {
                    ViewBag.ErrorMessage = result.Message;
                }


            }
            ResponseResult location = await locserv.Page(1, 100000, "");
            ViewBag.Location = new SelectList((List<LocationViewModel>)JsonConvert.DeserializeObject<List<LocationViewModel>>(location.Entity.ToString()), "id", "name");
            return PartialView("_Edit", model);
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {

            ResponseResult result = await TabServ.GetById(id);
            if (result != null)
            {
                return PartialView("_Delete", result.Entity);
            }
            return PartialView("_Delete", result.Entity);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(TabAlamatViewModel model)
        {
            if (ModelState.IsValid)
            {
                ResponseResult result = await TabServ.Delete(model);
                if (result.Success)
                {
                    ViewBag.title = "Delete";
                    ViewBag.subtitle = "Deleted";
                    return PartialView("_Success", model);
                }
                else
                {
                    ViewBag.ErrorMessage = result.Message;
                }

            }
            return PartialView("_Delete", model);
        }

        //[HttpGet]
        //public async Task<IActionResult> Search(string name)
        //{
        //    ResponseResult result = await bankServ.Search(name);
        //    if (result != null)
        //    {
        //        return PartialView("_List", result.Entity);
        //    }
        //    return PartialView("_List", result.Entity);

        //}

        [HttpGet]
        public async Task<IActionResult> ListPage(int page, int rows, string search, string column, bool ascen)
        {

            ResponseResult result = await TabServ.Page(page, rows, search, column, ascen);
            //TupleListCount listAccount = result.<>Entity;
            if (result.Success)
            {
                ViewBag.Pages = result.Pages;
                ViewData["SearchText"] = search;
            }
            else
            {
                ViewBag.ErrorMessage = result.Message;
            }
            List<TabAlamatViewModel> list = Newtonsoft.Json.JsonConvert.DeserializeObject<List<TabAlamatViewModel>>(result.Entity.ToString());
            return PartialView("_List", list);
        }

        public async Task<IActionResult> Columns()
        {

            return PartialView("_Columns", colList);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteMany(List<AlamatMultiCheckViewModel> model)
        {
            //if (ModelState.IsValid)
            //{
            //    ResponseResult result = await proServ.Delete(model);
            //    if (result.Success)
            //    {
            //        ViewBag.Title = "Delete";
            //        ViewBag.SubTitle = "deleted";
            //        return PartialView("_Success", model);
            //    }
            //    else
            //        ViewBag.ErrorMessage = result.Message;
            //}
            ResponseResult result = await TabServ.DeleteMany(model);
            if (result.Success)
            {
                return PartialView("_Success", new TabAlamatViewModel());
            }
            return PartialView("_Success", new TabAlamatViewModel());
        }

    }
}

MiniProject/WebApp/Controllers/UtilitiesController.cs
using Microsoft.AspNetCore.Mvc;
using ViewModel;

namespace WebApp.Controllers
{
    public class UtilitiesController : Controller
    {
        public IActionResult GetListRow()
        {
            return PartialView("_ListRow", Utilities.GetListRow());
        }
        
        public IActionResult Sorting()
        {
            return PartialView("_Sorting", Utilities.GetSortList());
        }
    }
}

MiniProject/WebApp/Views/TabAlamat/Index.cshtml
@using WebApp.Security

<div class="container emp-profile">
    <form method="post">
        <div class="row">
            <div class="col-md-3">
                <div class=" text-center">
                    <div class="profile-img">
                        <p>
                            <i class="col-md-12 fa fa-pencil text-left" aria-hidden="true"></i>
                            <img src="~/dist/img/user2-160x160.jpg" class="brand-image img-circle width="150" height="150" alt="Photo Profile">
                        </p>
                        <div class="profile-head">
                            <a class="proile-rating"><span>⭐</span></a>
                            <h4 class="text-primary">
                                @if (ContextAccessor.IsAuthenticated())
                                {
                                    <a>@ContextAccessor.GetFullName()</a>
                                }
                                Level Member
                            </h4>
                            <h6 class="font-weight-light">
                                Tahun daftar akun
                            </h6>
                        </div>
                        <p></p>
                    </div>
                    <br>
                    <br>
                    <br>
                    <div class="col-md-12 text-left">
                        <p class="text-primary font-weight-bolder">Pasien</p>
                        <p class="text-primary font-weight-bold"><a href="https://localhost:5002/m_medical_item">Pembelian Obat</a></p>
                        <p class="text-primary font-weight-bold">Rencana Kedatangan</p>
                        <p class="text-primary font-weight-bold">Riwayat Chat Dokter</p>
                    </div>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
            <div class="col-md-9">
                <div class="">
                    <ul class="nav nav-tabs" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" href="#profile" role="tab" data-toggle="tab">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#alamat" role="tab" data-toggle="tab">Alamat</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#pembayaran" role="tab" data-toggle="tab">Pembayaran</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#tariksaldo" role="tab" data-toggle="tab">Tarik Saldo</a>
                        </li>
                    </ul>

                    <!-- Tab panes -->
                    <div class="tab-content card">
                        <div role="tabpanel" class="tab-pane fade in active" id="profile">Data Pribadi</div>
                        <div role="tabpanel" class="tab-pane fade" id="alamat">
                            <div class="row card-body">
                            </div>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="pembayaran">
                            Ini Halaman pembayaran
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="tariksaldo">
                            <div class="row ">
                                <div class="col-6">
                                    <div class="card-body">
                                        <h5 class="card-title">Saldo saat ini : RP 450.000</h5>
                                        <br>
                                        <br>
                                        <button type="button" class="btn btn-primary">50.000</button>
                                        <button type="button" class="btn btn-primary">100.000</button>
                                        <button type="button" class="btn btn-primary">150.000</button>
                                        <br>
                                        <br>
                                        <button type="button" class="btn btn-primary">200.000</button>
                                        <button type="button" class="btn btn-primary">Nominal Lain</button>
                                        <br>
                                        <br>
                                        <br>
                                        <br>
                                        <br>
                                    </div>
                                    <div class="card-footer">
                                        <br>
                                        &nbsp;
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="card-body">
                                        <h5 class="card-title">Anda akan melakukan penarikan saldo sebesar : RP 100.000 </h5>
                                        <br>
                                        <br>
                                        <br>
                                        <button type="button" class="btn btn-primary col-md-12">Lanjutkan</button>
                                        <br>
                                        <br>
                                        <br>
                                        <br>
                                        <br>
                                        <br>
                                        <br>
                                    </div>
                                    <div class="card-footer">
                                        <div class="pull-right ml-auto">
                                            <button type="button" class="btn btn-danger">Cancle</button>
                                            <button type="button" class="btn btn-primary">OK</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--<div class="row">
                <div class="col-md-4">
                    <div class="card">
                        <div class="col-md-12 text-left">
                            <p></p>
                            <p class="text-primary font-weight-bolder">Tentang Saya</p>
                            <p class="text-primary font-weight-bold">Tindakan Medis</p>
                            <p></p>
                            <p class="text-primary font-weight-bold">Riwayat Praktek</p>
                            <div class="col-md-12 text-left">
                                <a>RS Mitra, Depok</a>
                                <pre>Dokter Anak	2019 - sekarang</pre>
                                <a>RSIA Bunda, Jakarta Pusat</a>
                                <pre>Dokter Anak	2018 - sekarang</pre>
                                <a>RSUP Hasan Sadikin, Bandung</a>
                                <pre>Dokter Anak	    2016 - 2018</pre>
                            </div>
                            <p class="text-primary font-weight-bold">Pendidikan</p>
                            <div class="col-md-12 text-left">
                                <a>Universitas Padjajaran</a>
                                <pre>Spesialis Anak		   2016</pre>
                                <a>Universitas Padjajaran</a>
                                <pre>Keddokteran Umuum	   2011</pre><br />
                            </div>
                        </div>
                    </div>
                </div>-->
            @*<div class="col-md-8">
            <div class="tab-content profile-tab" id="myTabContent">
            <div class="tab-panel fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
            </div>
            <div class="tab-panel fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
            </div>
            </div>
            </div>*@
            <!--</div>-->
    </form>
</div>
</div>

<!-- Modal -->
<div class="modal fade" id="form-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-label">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            @*<div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
            </div>*@
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        var currentPage = 1;
        var rowsPerpage = 5;
        var currentSearch = "";
        var currentcolumn = "label";
        var currentascen = "true";
        $(document).ready(function () {
            GetList(currentPage, rowsPerpage, currentSearch, currentcolumn, currentascen);
        })

        function GetList(page, rows, search, column, ascen) {
            currentPage = page;
            rowsPerpage = rows;
            currentSearch = search;
            currentcolumn = column;
            currentascen = ascen;
            $.ajax({
                url: '@Url.Action("ListPage")',
                type: 'get',
                data: { page: page, rows: rowsPerpage, search: currentSearch, column: currentcolumn, ascen: currentascen },
                success: function (result) {
                    $("#alamat").html(result)
                }
            });
        }


        //function GetList(){
        //    $.ajax({
        //        url:'@Url.Action("List")',
        //        type:'get',
        //        success: function(result) {
        //            $('#panel-body').html(result)
        //        }
        //    })
        //}

        $('#btn-create').click(function () {
            $.ajax({
                url: '@Url.Action("Create")',
                type: 'get',
                success: function (result) {
                    $('.modal-body').html(result)
                }
            })
            $('.modal-title').html('Create New')
            $('#form-modal').modal('show');
        });
    </script>
}

MiniProject/WebApp/Views/TabAlamat/_Columns.cshtml
@model IEnumerable<ViewModel.ListValue>

<select id="column-list-ctrl" class="custom-select">
@*    @foreach (var item in @Model)
    {
        <option id="@item.Value" value="@item.Value">@item.Value</option>
    }*@
</select>

<script>
    //$(document).ready(function(){
    //    $('#column-list-ctrl').val(currentcolumn)
    //})

    //$('#column-list-ctrl').on('change', function(){
    //    GetList(currentPage, rowsPerpage, currentSearch, $(this).val(), currentascen);
    //})
</script>

MiniProject/WebApp/Views/TabAlamat/_Create.cshtml
@model ViewModel.TabAlamatViewModel


<div class="row">
    <div class="col-md-12">
        <form asp-action="Create" method="post" id="form-create" Nama="form-create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="biodata_id" class="control-label"></label>
                <input asp-for="biodata_id" class="form-control" />
                <span asp-validation-for="biodata_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="label" class="control-label"></label>
                <input asp-for="label" class="form-control" />
                <span asp-validation-for="label" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="recipient" class="control-label"></label>
                <input asp-for="recipient" class="form-control" />
                <span asp-validation-for="recipient" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="recipient_phone_number" class="control-label"></label>
                <input asp-for="recipient_phone_number" class="form-control" />
                <span asp-validation-for="recipient_phone_number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="kota" class="control-label"></label>
                @Html.DropDownListFor(model => model.location_id, (IEnumerable<SelectListItem>)ViewBag.Location, "Pilih Kota", new { @class = "form-control" })
                <span asp-validation-for="kota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="postal_code" class="control-label"></label>
                <input asp-for="postal_code" class="form-control" />
                <span asp-validation-for="postal_code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address" class="control-label"></label>
                <input asp-for="address" class="form-control" />
                <span asp-validation-for="address" class="text-danger"></span>
            </div>
            <p class="text-danger">@ViewBag.ErrorMessage</p>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <input type="button" value="Cancel" data-dismiss="modal" class="btn btn-danger" />
            </div>
        </form>
    </div>
</div>

<script>
    $('#form-create').submit(function () {
        var dataForm = new FormData($(this)[0]);
        console.log(dataForm);
        $.ajax({
            url: this.action,
            type: this.method,
            data: dataForm,
            processData: false,
            contentType: false,
            success: function (result) {
                $('.modal-body').html(result);
            }
        })
        return false;
    });
</script>

MiniProject/WebApp/Views/TabAlamat/_Delete.cshtml
@model ViewModel.TabAlamatViewModel

<h3>Anda yakin ingin menghapus @Html.DisplayFor(model => model.recipient)?</h3>
<div>
    <form asp-action="Delete" method="post" id="form-delete" name="form-delete">
        @Html.HiddenFor(model => model.id)
        @Html.HiddenFor(model => model.label)
        @Html.HiddenFor(model => model.biodata_id)
        @Html.HiddenFor(model => model.recipient)
        @Html.HiddenFor(model => model.recipient_phone_number)
        @Html.HiddenFor(model => model.location_id)
        @Html.HiddenFor(model => model.postal_code)
        @Html.HiddenFor(model => model.address)
        <input type="submit" value="Delete" class="btn btn-danger" onclick="GetList(currentPage, rowsPerpage, currentSearch, currentcolumn, currentascen)" />
        <input type="button" value="Cancel" data-dismiss="modal" class="btn btn-secondary" />
    </form>
</div>

<script type="text/javascript">
    $('#form-delete').submit(function () {
        var dataForm = new FormData($(this)[0]);
        $.ajax({
            url: this.action,
            type: this.method,
            data: dataForm,
            processData: false,
            contentType: false,
            success: function (result) {
                $('.modal-body').html(result);
            }
        })
        return false;
    });
</script>

MiniProject/WebApp/Views/TabAlamat/_List.cshtml
@model IEnumerable<ViewModel.TabAlamatViewModel>

<table class="table list-table">
    <thead>
        <div class="container">
            <div class="row">
                <div class="input-group col-8">
                    <input type="text" class="form-control rounded btn-input" id="myInput" value="@ViewData["SearchText"]" placeholder="Search by Label" aria-label="Search" aria-describedby="search-addon" />
                        <button type="submit" class="btn btn-outline-primary btn-search" id="searching">Search</button>
                </div>
            </div>
            <div class="row">
                <br />
            </div>
            <div class="row">
                <div class="input-group col-8">
                    <button type="button" class="btn btn-danger fa fa-trash id = "btn-deleteAll"> Hapus</button>
                </div>
                <div>
                    |<button type="button" class="btn btn-link fa fa-user-plus" id="btn-create"> Tambah</button>
                </div>
            </div>
        </div>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.CheckBoxFor(modelItem => item.Check)
                    @Html.HiddenFor(modelItem => item.id)
                </td>
                <td>
                    <div style="color:deepskyblue"><font size="+2">@Html.DisplayFor(modelItem => item.label)</font></div>
                    <div>@Html.DisplayFor(modelItem => item.recipient) , @Html.DisplayFor(modelItem => item.recipient_phone_number)</div>
                    <div>@Html.DisplayFor(modelItem => item.address), @Html.DisplayFor(modelItem => item.kota)</div>
                </td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <button type="button" class="btn btn-info btn-edit" data-id="@item.id"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
                        <button type="button" class="btn btn-danger btn-delete" data-id="@item.id"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class=row>
    <div class="col-md-7">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                @for (int I = 1; I <= ViewBag.Pages; I++)
                {
                    <li class="page-item"><a class="page-link btn-link-page" data-id="@I" onclick="GetList(@I, rowsPerpage, currentSearch, currentcolumn, currentascen)">@I</a></li>
                }
            </ul>
        </nav>
    </div>

    <div class="col-md-4" id="column-list">
    </div>

</div>


<script>

    $(document).ready(function () {
        GetController();
        //$("#list-page").val(rowsPerpage);
    })

    $('.btn-edit').click(function () {
        $.ajax({
            url: '@Url.Action("Edit")',
            type: 'get',
            data: { id: $(this).attr('data-id') },
            success: function (result) {
                $('.modal-title').html('Edit');
                $('.modal-body').html(result);
                $('#form-modal').modal('show');
            }
        })
    });

    function GetController() {
        $.ajax({
            url: '@Url.Action("GetListRow","Utilities")',
            type: 'get',
            success: function (result) {
                $('#row-page').html(result);
            }
        })

        $.ajax({
            url: '@Url.Action("Sorting","Utilities")',
            type: 'get',
            success: function (result) {
                $('#column-list').html(result);
            }
        })
        $.ajax({
            url: '@Url.Action("Columns","TabAlamat")',
            type: 'get',
            success: function (result) {
                $('#sorting-list').html(result);
            }
        })

    }

    $('.btn-delete').click(function () {
        $.ajax({
            url: '@Url.Action("Delete")',
            type: 'get',
            data: { id: $(this).attr('data-id') },
            success: function (result) {
                $('.modal-title').html('Delete');
                $('.modal-body').html(result);
                $('#form-modal').modal('show');
            }
        })
    });

    $('#btn-create').click(function () {
        $.ajax({
            url: '@Url.Action("Create")',
            type: 'get',
            success: function (result) {
                $('.modal-body').html(result);
            }
        })
        $('.modal-title').html('Tambah Pasien');
        $('#form-modal').modal('show');
    });
    $('#btn-deleteAll').click(function () {
        var details = [];
        $(".list-table tbody").find('tr').each(function () {
            var id = $(this).find("input[id=item_id]").val();
            var checked = $(this).find("input[id=item_Check]").is(":checked");
            var detail = {
                Id: id,
                Check: checked
            }
            details.push(detail);
        });
        $.ajax({
            url: '@Url.Action("DeleteMany")',
            type: 'post',
            data: { model: details },
            success: function (result) {
                $('.modal-body').html(result);
                $('.modal-title').html('Update list');
                $('#form-modal').modal('show');
            }
        })
    })


</script>

MiniProject/WebApp/Views/TabAlamat/_Success.cshtml
@model ViewModel.TabAlamatViewModel
@{
    string customStyle = "";
    switch (ViewBag.title)
    {
        case "Create":
            customStyle = "text-success";
            break;
        case "Edit":
            customStyle = "text-warning";
            break;
        default:
            customStyle = "text-danger";
            break;
    }
}
<h3 class="@customStyle">@ViewBag.title successful!</h3>
<p>@Html.DisplayFor(model => model.label) @ViewBag.subtitle!</p>
<input type="button" value="Close" data-dismiss="modal" onclick="GetList(currentPage, rowsPerpage, currentSearch, currentcolumn, currentascen)" class="btn btn-danger" />
<script>
    type = "text/javascript" >
        $(document).ready(function () {
            GetList(currentPage, rowsPerpage, currentSearch, currentcolumn, currentascen);
        });
</script>